# Generated by Django 3.0.7 on 2025-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20250112_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
